import type { Metadata } from "next";
import { Inter, IBM_Plex_Sans } from "next/font/google";
import "./globals.css";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });
const plex = IBM_Plex_Sans({ subsets: ["latin"], weight: ["100", "200", "300", "400", "500", "600", "700"] });

export const metadata: Metadata = {
  title: "EASY-GOLF",
  description: "Egal welche Größe der Golfer hat, die Winkel bleiben gleich. Die wird durch individuelle Anpassung der Schlägerlänge erreicht.",
  keywords: [
    'Golfspiel',
    'Golf',
    'golf club',
    'Golfschläger',
    'Schlägerbau',
    'Golfset',
    'golf setup',
    'golf shaft',
    'Golfschaft',
    'biometrisch',
    'geometrisch',
    'Fitting',
    'club fitting',
    'Schwunggewicht',
    'swing weight',
    'Pinkafeld',
    'EASY-GOLF',
    'easy golf',
    'easygolf',
    'easy golfen',
    'easy golfen mit easy-golf',
    'einfach golfen',
    'golfen leicht gemacht',
    'PXG',
    'TourEdge',
    'Exotics',
    'Golfball',
    'Eisen',
    'irons',
    'Holz',
    'Wood',
    'Wedges',
    'Putter',
    'Chipper',
    'chippen',
    'pitchen',
    'Driver',
    'Schlägerkopf',
    'club head',
    'Golfgriff',
    'grip size',
    'golf grip',
    'Ferrule',
    'Tape',
    'Jeff Summitt',
    'Dave Tutelman',
    'Tom Wishon',
    'Ralph Malty',
    'club making',
    'club building',
    'Golfkomponente',
    'golf components',
    'Schwerpunkt',
    'balence point',
    'Golfgeschäft',
    'Pro-Shop',
    'Golf',
    'Golfer',
    'Golferin',
    'Golfspieler',
    'Golfzeitschrift',
    'Schlagroboter',
    'Iron Byron',
    'Körpergröße',
    'Schlagweite',
    'distance',
    'Konstanz',
    'constant',
    'sweet spot',
    'Hobbygolfer',
    'Amateurgolfer',
    'Golfschwung',
    'Schwungtechnik',
    'Loft',
    'Lie',
    'Ballflug',
    'Slice',
    'Draw',
    'Hook',
    'Fade',
    'Demo-Day',
    'Body Geometry Fitting',
    'Geometrie',
    'nach Maß',
    'custom fitting',
    'Fertigungstoleranzen',
    'Golf-Pro',
    'Golftrainer',
    'Schlägersatz',
    'Flexgrad',
    'Schaftflex',
    'shaft flex',
    'bending',
    'EI profile',
    'shaft profile',
    'spine',
    'nbp',
    'flo',
    'moi',
    'frequency',
    'matching',
    'Gelenk-Drehpunkte',
    'Körper-Geometrie',
    'Fachgeschäft',
    'Fachwissen',
    'Golfsport',
    'Rumpfwinkel',
    'Ballflug',
    'Single-Length',
    'Golfrunde',
    'kurzes Spiel',
    'Pitching',
    'Bunker',
    'Shaft Alignment',
    'Frequenz-Messung',
  ]
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" style={{ scrollBehavior: 'smooth' }}>
      <head>
        <link rel="icon" href="favicon.ico" />
        <link rel="manifest" href="site.webmanifest" />
      </head>
      <body className={plex.className}>{children}</body>
    </html>
  );
}
